version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    nuget restore

    $env:SHARPYAML_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
   
    $env:SHARPYAML_VERSION_SUFFIX = "pre$env:SHARPYAML_BUILD_NUMBER"

    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      $env:appveyor_nuget_push = 'true'
      if($env:appveyor_repo_tag -eq 'True') {
    	  if($env:appveyor_repo_tag_name -match '^v[0-9]') {
           $env:SHARPYAML_VERSION_SUFFIX = ""
        }
      }
    }
build:
  project: SharpYaml.sln
  verbosity: minimal
before_package:
- cmd: msbuild /t:pack /p:VersionSuffix="%SHARPYAML_VERSION_SUFFIX%" /p:Configuration=Release SharpYaml/SharpYaml.csproj
artifacts:
- path: SharpYaml\Bin\Release\*.nupkg
  name: SharpYaml Nugets
deploy:
- provider: NuGet
  api_key:
    secure: 7cthHh+wYWZjhqxaxR6QObRaRnstvFkQOY7MkxIsC5kpQEBlKZXuinf0IybbYxJt
  on:
    appveyor_nuget_push: true